(()=>{'use strict';
const NOTES=['C','D','E','F','G','A','B'],NAMES={C:'Dó',D:'Ré',E:'Mi',F:'Fá',G:'Sol',A:'Lá',B:'Si',Eb:'Mi♭'},HZ={C:261.63,D:293.66,E:329.63,F:349.23,G:392,A:440,B:493.88,Eb:311.13};
const MODULES=[
{id:1,icon:'👂',title:'Fundamentos do Ouvido',range:'Áudios 01–50',desc:'Grave/agudo, igual/diferente, direção, reconhecimento de notas e memória.',lessons:['Perceber altura','Reconhecer 2 notas','Ampliar o mapa','Memorizar sons','Teste de prontidão']},
{id:2,icon:'🏠',title:'Tonalidade e Graus',range:'Áudios 51–120',desc:'Tônica, centro tonal, escala maior, graus e funções musicais.',lessons:['Sensação de casa','Encontrar a tônica','Graus da escala','I–IV–V','Teste de tonalidade']},
{id:3,icon:'↔️',title:'Intervalos e Melodia',range:'Áudios 121–180',desc:'Distâncias entre notas, direção, contorno, canto e reprodução melódica.',lessons:['Passos e saltos','Intervalos','Contorno','Eco melódico','Ditado auditivo']},
{id:4,icon:'🎼',title:'Acordes e Harmonia',range:'Áudios 181–260',desc:'Tríades, maior/menor, baixo, inversões, progressões e tensão/resolução.',lessons:['Ouvir acordes','Maior × menor','Baixo','I–IV–V','Progressões']},
{id:5,icon:'🎤',title:'Descobrindo Músicas de Ouvido',range:'Áudios 261–300',desc:'Descobrir a tonalidade de músicas, inclusive quando o cantor começa fora da tônica.',lessons:['Encontrar repouso','Maior ou menor','Nota inicial ≠ tônica','Transposição/capo','Desafio de música']},
{id:6,icon:'🏆',title:'Testes e Diagnóstico',range:'Áudios 301–320',desc:'Avaliação integrada, pontos fracos, reforço e preparação para tocar de ouvido.',lessons:['Diagnóstico','Notas','Tonalidade','Harmonia','Desafio final']}
];
let ctx=null,state=load(),route='home',currentModule=1;
function fresh(){return{xp:0,attempts:0,correct:0,streak:0,level:1,skills:{note:0,tonic:0,interval:0,chord:0,song:0}}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem('pom_v5')||'{}'))}catch(e){return fresh()}}
function save(){localStorage.setItem('pom_v5',JSON.stringify(state));const x=document.getElementById('xp');if(x)x.textContent='⚡ '+state.xp+' XP'}
function accuracy(){return state.attempts?Math.round(state.correct/state.attempts*100):0}
async function audio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;ctx=ctx||new AC;if(ctx.state==='suspended')try{await ctx.resume()}catch(e){}return ctx}
async function note(n,d=.55,delay=0){const c=await audio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type='triangle';o.frequency.value=HZ[n];g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.16,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.03)}
async function play(a){await audio();a.forEach((n,i)=>note(n,.55,i*.64))}
function render(h){document.getElementById('app').innerHTML=h;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('on',b.dataset.route===route));save();window.scrollTo({top:0,behavior:'smooth'})}
function home(){route='home';render(`<section class="hero"><span class="eyebrow">Percep-O-Musical • Curso completo</span><h1>Treine o ouvido como um músico.</h1><p>Aprenda do zero e avance até descobrir tonalidades, melodias e harmonia de músicas reais.</p><div class="row"><button class="btn" data-route="modules">▶ Ver módulos</button><button class="btn alt" data-route="memory">🧠 Treinar memória</button></div></section><div class="card"><h2>Seu progresso</h2><div class="stats"><div class="stat"><b>${accuracy()}%</b><small>precisão</small></div><div class="stat"><b>${state.streak}</b><small>sequência</small></div><div class="stat"><b>${state.level}</b><small>nível</small></div></div></div><div class="callout"><b>Método:</b> Aprender → Ouvir → Praticar → Diagnosticar → Reforçar → Testar → Avançar.</div><div class="grid">${MODULES.slice(0,3).map(m=>cardModule(m)).join('')}</div>`)}
function cardModule(m){return `<article class="card"><span class="badge">MÓDULO ${m.id} • ${m.range}</span><h3>${m.icon} ${m.title}</h3><p>${m.desc}</p><button class="btn" data-module="${m.id}">Abrir módulo</button></article>`}
function modules(){route='modules';render(`<section class="hero"><span class="eyebrow">Trilha completa</span><h1>6 módulos, 6 habilidades diferentes.</h1><p>Cada módulo tem objetivo, teoria, prática, diagnóstico e progressão próprios. Não são cópias do mesmo exercício.</p></section><div class="grid">${MODULES.map(cardModule).join('')}</div>`)}
function modulePage(id){const m=MODULES.find(x=>x.id===id)||MODULES[0];currentModule=m.id;route='module';render(`<section class="hero"><span class="eyebrow">Módulo ${m.id} • ${m.range}</span><h1>${m.icon} ${m.title}</h1><p>${m.desc}</p><div class="callout"><b>Objetivo:</b> ${m.lessons[0]}. Você vai ouvir primeiro, entender depois e só então receber o nome teórico.</div></section><div class="card"><h2>Trilha deste módulo</h2>${m.lessons.map((x,i)=>`<div class="lesson"><span>${i+1}</span><div><b>${x}</b><small>${lessonText(m.id,i)}</small></div><button class="btn miniBtn" data-lesson="${m.id}-${i}">Abrir</button></div>`).join('')}</div><div class="card"><h2>Aplicação musical</h2><p>${application(m.id)}</p><button class="btn" onclick="startModuleChallenge(${m.id})">🎧 Praticar agora</button><div id="challenge"></div></div><button class="btn alt" data-route="modules">← Voltar aos módulos</button>`)}
function lessonText(id,i){const a=[['Perceba antes de nomear.','Compare sons sem precisar saber seus nomes.'],['Reconheça relações.','Comece com poucas possibilidades e aumente gradualmente.'],['Construa memória.','Ouça, silencie e tente recuperar o som.'],['Consolide.','Use a habilidade em uma situação musical.'],['Teste.','O resultado define se você avança ou reforça.']];return (a[(i+id)%a.length]||a[0])[1]}
function application(id){return id===1?'Reconhecer alturas é a base para encontrar notas cantadas.':id===2?'Encontrar a tônica permite descobrir o centro da música mesmo quando a primeira nota é outra.':id===3?'Intervalos e contorno ajudam a reproduzir uma melodia sem depender de cifras.':id===4?'Ouvir a qualidade do acorde conecta o ouvido às progressões que você toca.':id===5?'Aqui juntamos tudo: cantor, tônica, modo, violão e transposição.':'O diagnóstico final mostra quais habilidades precisam de reforço antes de avançar.'}
function memory(){route='memory';render(`<section class="hero"><span class="eyebrow">Memória auditiva</span><h1>🧠 Ouça. Silencie. Recupere.</h1><p>Memória auditiva sustenta reconhecimento de notas, intervalos, melodias e tonalidade.</p></section><div class="grid"><article class="card"><h3>Nota</h3><p>Guarde uma altura e escolha entre quatro nomes.</p><button class="btn" onclick="memoryNote()">Começar</button></article><article class="card"><h3>Sequência</h3><p>Reconstrua uma sequência que cresce com seu nível.</p><button class="btn" onclick="memorySequence()">Começar</button></article><article class="card"><h3>Contorno</h3><p>Memorize somente sobe, desce ou repete.</p><button class="btn" onclick="memoryContour()">Começar</button></article></div><div id="mem"></div>`)}
function choices(correct,vals){return [...new Set([correct,...vals])].slice(0,4).sort(()=>Math.random()-.5)}
function memoryUI(title,a,opts,correct){document.getElementById('mem').innerHTML=`<article class="card"><span class="eyebrow">${title}</span><div class="memory"><strong>🎧</strong><p>Ouça e depois responda sem repetir.</p><button class="listen" onclick="play(${JSON.stringify(a)})">▶ Ouvir</button></div><div class="choices">${opts.map(x=>`<button class="choice" onclick="answerMemory(this,'${x.replace(/'/g,"\\'")}','${correct.replace(/'/g,"\\'")}')">${x}</button>`).join('')}</div><div id="mfb"></div></article>`}
function memoryNote(){const n=NOTES[Math.floor(Math.random()*7)],c=NAMES[n],o=choices(c,NOTES.map(x=>NAMES[x]));memoryUI('Memória de uma nota',[n],o,c)}
function memorySequence(){const len=Math.min(2+Math.floor((state.level-1)/2),5),a=Array.from({length:len},()=>NOTES[Math.floor(Math.random()*7)]),c=a.map(x=>NAMES[x]).join(' → '),w=[a.slice().reverse().map(x=>NAMES[x]).join(' → '),a.map(x=>NAMES[NOTES[(NOTES.indexOf(x)+1)%7]]).join(' → '),'Outra sequência'];memoryUI('Memória de sequência',a,choices(c,w),c)}
function memoryContour(){const sets=[['C','E','D'],['E','C','G'],['C','D','E'],['G','E','C']],labels=['↑ ↑ ↓','↓ ↑ ↑','↑ ↑ ↑','↓ ↓ ↓'],i=Math.floor(Math.random()*sets.length);memoryUI('Memória de contorno',sets[i],labels,labels[i])}
function answerMemory(btn,a,c){const good=a===c;state.attempts++;if(good){state.correct++;state.xp+=10;state.streak++;state.level=Math.min(10,state.level+1)}else{state.streak=0;state.level=Math.max(1,state.level-1)}btn.classList.add(good?'good':'bad');document.getElementById('mfb').innerHTML=`<div class="feedback ${good?'ok':'no'}"><b>${good?'✓ Correto':'↺ Reforço'}</b><br>${good?'Você recuperou a informação auditiva.':'A resposta correta é '+c+'. Ouça novamente e tente perceber a relação.'}</div>`;save()}
function apply(){route='apply';render(`<section class="hero"><span class="eyebrow">Aplicação</span><h1>👂 Ouvido → 🎸 música</h1><p>Agora a teoria deixa de ser abstrata.</p></section><article class="card"><h2>Maior × menor</h2><p>A diferença está na terça.</p><div class="row"><button class="btn" onclick="play(['C','E','G'])">▶ C maior</button><button class="btn alt" onclick="play(['C','Eb','G'])">▶ C menor</button></div><div class="callout">C–E–G = maior • C–E♭–G = menor.</div></article><article class="card"><h2>🎤 Cantor começa fora da tônica</h2><p>A primeira nota pode ser outro grau. O centro tonal é encontrado pela sensação de repouso.</p><button class="btn" onclick="startModuleChallenge(5)">Iniciar desafio</button><div id="challenge"></div></article>`)}
function startModuleChallenge(id){const box=document.getElementById('challenge');if(!box)return;const tonic=NOTES[Math.floor(Math.random()*7)],start=NOTES[(NOTES.indexOf(tonic)+2)%7];box.innerHTML=`<div class="callout"><b>Trecho:</b> o cantor começa em ${NAMES[start]}. Depois a música repousa em ${NAMES[tonic]}.<br><br><b>Qual é a tônica?</b><div class="choices">${NOTES.map(n=>`<button class="choice" onclick="challengeAnswer('${n}','${tonic}')">${NAMES[n]}</button>`).join('')}</div></div>`}
function challengeAnswer(a,c){const good=a===c;state.attempts++;if(good){state.correct++;state.xp+=15;state.streak++}else state.streak=0;document.getElementById('challenge').insertAdjacentHTML('beforeend',`<div class="feedback ${good?'ok':'no'}">${good?'✓ Perfeito. Você separou nota inicial de centro tonal.':'↺ A tônica era '+NAMES[c]+'. Procure o repouso, não a primeira nota.'}</div>`);save()}
function guitar(){route='guitar';render(`<section class="hero"><span class="eyebrow">Laboratório de violão</span><h1>🎸 Encontre o som no braço.</h1><p>Afinação padrão: E–A–D–G–B–E. Primeiro ouça, depois procure.</p></section><article class="card"><h2>Alvo auditivo</h2><div class="row">${NOTES.map(n=>`<button class="btn" onclick="note('${n}');document.getElementById('target').textContent='Alvo: '+NAMES['${n}']">${NAMES[n]}</button>`).join('')}</div><div id="target" class="callout">Escolha uma nota e tente localizá-la no braço.</div></article><article class="card"><h2>Braço simplificado</h2><div class="neck">${['E','A','D','G','B','E'].map((s,i)=>`<div class="string"><b>${s}</b>${[0,1,2,3,4,5,7,9,12].map(f=>`<span class="fret">${f}</span>`).join('')}</div>`).join('')}</div><p class="mini">A visualização será expandida para marcação automática de notas e exercícios por corda/traste.</p></article>`)}
function diagnostics(){route='diagnostic';render(`<section class="hero"><span class="eyebrow">Diagnóstico</span><h1>🏆 Seu mapa auditivo</h1><p>Use os resultados para saber o que reforçar.</p></section><div class="card"><div class="stats"><div class="stat"><b>${accuracy()}%</b><small>precisão geral</small></div><div class="stat"><b>${state.xp}</b><small>XP</small></div><div class="stat"><b>${state.level}</b><small>nível adaptativo</small></div></div><div class="callout gold">Não avançaremos apenas porque você terminou exercícios. Domínio será baseado em desempenho.</div></div>`)}
function bind(){document.addEventListener('click',e=>{const r=e.target.closest('[data-route]'),m=e.target.closest('[data-module]');if(r){const x=r.dataset.route;({home,modules,memory,apply,guitar,diagnostics}[x]||home)()}if(m)modulePage(Number(m.dataset.module));});}
window.note=note;window.play=play;window.memoryNote=memoryNote;window.memorySequence=memorySequence;window.memoryContour=memoryContour;window.answerMemory=answerMemory;window.challengeAnswer=challengeAnswer;window.startModuleChallenge=startModuleChallenge;bind();home();
})();