(()=>{'use strict';
const NOTES=['C','D','E','F','G','A','B'],N={C:'Dó',D:'Ré',E:'Mi',F:'Fá',G:'Sol',A:'Lá',B:'Si',Eb:'Mi♭'},HZ={C:261.63,D:293.66,E:329.63,F:349.23,G:392,A:440,B:493.88,Eb:311.13};
const MODULES=[
{id:1,icon:'👂',title:'Fundamentos do Ouvido',range:'Áudios 01–50',desc:'Aprenda a perceber altura antes de precisar saber nomes.',lessons:[['Perceber altura','Descobrir grave e agudo sem teoria.'],['Igual ou diferente','Comparar duas alturas.'],['Direção sonora','Perceber sobe, desce ou repete.'],['Reconhecer notas','Começar a ligar som e nome.'],['Prontidão','Verificar se a base está firme.']]},
{id:2,icon:'🏠',title:'Tonalidade e Graus',range:'Áudios 51–120',desc:'Descubra a sensação de casa e organize as notas ao redor da tônica.',lessons:[['Sensação de casa','Ouvir repouso e tensão.'],['Encontrar a tônica','Separar centro tonal da nota inicial.'],['Graus da escala','Perceber funções dos graus.'],['I–IV–V','Reconhecer a base de muitas músicas.'],['Teste de tonalidade','Descobrir o centro sem receber a resposta.']]},
{id:3,icon:'↔️',title:'Intervalos e Melodia',range:'Áudios 121–180',desc:'Entenda distância, direção e contorno para reproduzir melodias.',lessons:[['Passos e saltos','Distinguir movimento conjunto de salto.'],['Tamanho do intervalo','Comparar distâncias sonoras.'],['Contorno','Enxergar a forma da melodia pelo ouvido.'],['Eco melódico','Ouvir e reproduzir pequenas frases.'],['Ditado auditivo','Transformar o que ouviu em informação.']]},
{id:4,icon:'🎼',title:'Acordes e Harmonia',range:'Áudios 181–260',desc:'Ouça maior, menor, baixo, movimento harmônico e tensão/resolução.',lessons:[['Ouvir acordes','Reconhecer som simultâneo.'],['Maior × menor','Usar a terça como pista.'],['Ouvir o baixo','Perceber a nota mais grave.'],['I–IV–V','Reconhecer funções harmônicas.'],['Progressões','Antecipar movimento e resolução.']]},
{id:5,icon:'🎤',title:'Descobrindo Músicas de Ouvido',range:'Áudios 261–300',desc:'Junte ouvido, voz e violão para descobrir o tom de músicas reais.',lessons:[['Encontrar repouso','Procurar a nota que soa como casa.'],['Maior ou menor','Usar o caráter da terça e do acorde.'],['Nota inicial ≠ tônica','Não cair na armadilha da primeira nota.'],['Transposição e capo','Levar a descoberta para o violão.'],['Desafio de música','Resolver uma situação musical completa.']]},
{id:6,icon:'🏆',title:'Testes e Diagnóstico',range:'Áudios 301–320',desc:'Meça habilidades, encontre pontos fracos e receba o próximo treino.',lessons:[['Diagnóstico inicial','Mapear o ouvido antes de avançar.'],['Teste de notas','Medir reconhecimento de alturas.'],['Teste de tonalidade','Medir centro tonal.'],['Teste de harmonia','Medir acordes e funções.'],['Desafio final','Integrar tudo em uma decisão musical.']]}
];
let ctx=null,route='home',current={m:1,l:0},state=load();
function fresh(){return{xp:0,attempts:0,correct:0,streak:0,level:1,skills:{note:0,tonic:0,interval:0,chord:0,song:0},lessons:{}}}
function load(){try{const x=JSON.parse(localStorage.getItem('pom_v6')||'{}');return Object.assign(fresh(),x,{skills:Object.assign(fresh().skills,x.skills||{}),lessons:x.lessons||{}})}catch(e){return fresh()}}
function save(){localStorage.setItem('pom_v6',JSON.stringify(state));const x=document.getElementById('xp');if(x)x.textContent='⚡ '+state.xp+' XP'}
function acc(){return state.attempts?Math.round(state.correct/state.attempts*100):0}
async function audio(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;ctx=ctx||new A;if(ctx.state==='suspended')try{await ctx.resume()}catch(e){}return ctx}
async function tone(n,d=.55,delay=0){const c=await audio();if(!c||!HZ[n])return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type='triangle';o.frequency.value=HZ[n];g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.15,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.03)}
async function play(a){await audio();a.forEach((n,i)=>tone(n,.5,i*.58))}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/'/g,'&#39;')}
function render(h){const app=document.getElementById('app');if(!app)return;app.innerHTML=h;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('on',b.dataset.route===route));save();window.scrollTo(0,0)}
function home(){route='home';render(`<section class="hero"><span class="eyebrow">Percep-O-Musical • Curso completo</span><h1>Treine o ouvido como um músico.</h1><p>Comece do zero. Aprenda o conceito, ouça, pratique e só avance quando entender.</p><div class="row"><button class="btn" data-route="modules">▶ Começar curso</button><button class="btn alt" data-route="memory">🧠 Treinar memória</button></div></section><div class="card"><h2>Seu ponto de partida</h2><div class="stats"><div class="stat"><b>${acc()}%</b><small>precisão</small></div><div class="stat"><b>${state.streak}</b><small>sequência</small></div><div class="stat"><b>${state.level}</b><small>nível</small></div></div></div><div class="callout"><b>Como vamos estudar:</b> Aprender → Ouvir → Praticar → Diagnosticar → Reforçar → Testar → Avançar.</div><div class="grid">${MODULES.slice(0,3).map(card).join('')}</div>`)}
function card(m){return `<article class="card"><span class="badge">MÓDULO ${m.id} • ${m.range}</span><h3>${m.icon} ${m.title}</h3><p>${m.desc}</p><button class="btn" data-module="${m.id}">Abrir módulo</button></article>`}
function modules(){route='modules';render(`<section class="hero"><span class="eyebrow">Trilha completa</span><h1>6 módulos. 6 habilidades.</h1><p>Não são seis cópias do mesmo exercício. Cada módulo muda a pergunta que o seu ouvido precisa responder.</p></section><div class="grid">${MODULES.map(card).join('')}</div>`)}
function modulePage(id){const m=MODULES.find(x=>x.id===id)||MODULES[0];current.m=m.id;route='module';render(`<section class="hero"><span class="eyebrow">Módulo ${m.id} • ${m.range}</span><h1>${m.icon} ${m.title}</h1><p>${m.desc}</p><div class="callout"><b>Regra:</b> primeiro experimente com o ouvido; depois leia a explicação. O objetivo é reconhecer, entender, nomear e aplicar.</div></section><div class="card"><h2>Trilha de aprendizagem</h2>${m.lessons.map((x,i)=>`<div class="lesson"><span>${i+1}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><button class="btn miniBtn" data-lesson="${m.id}-${i}">${state.lessons[m.id+'-'+i]?'Rever':'Abrir'}</button></div>`).join('')}</div><button class="btn alt" data-route="modules">← Voltar</button>`)}
const LESSONS={
'1-0':{title:'Descobrindo grave e agudo',theory:'Altura é a percepção de quão grave ou agudo um som parece. Você não precisa saber o nome da nota para perceber isso.',goal:'Perceber qual de dois sons está mais alto.',kind:'height'},
'1-1':{title:'Igual ou diferente?',theory:'Antes de identificar notas, seu ouvido precisa comparar. Dois sons podem ter a mesma altura ou alturas diferentes.',goal:'Comparar duas alturas.',kind:'same'},
'1-2':{title:'A melodia sobe ou desce?',theory:'Direção é a relação entre uma nota e a seguinte. Uma melodia pode subir, descer ou repetir.',goal:'Identificar a direção do movimento.',kind:'direction'},
'1-3':{title:'Ligando som e nome',theory:'Agora começamos a associar uma altura a um nome. Isso será construído gradualmente, não decorado de uma vez.',goal:'Reconhecer uma nota entre poucas opções.',kind:'note'},
'1-4':{title:'Teste de prontidão',theory:'Este teste verifica se você domina a base. Errar não é fracasso: indica o que precisa ser repetido.',goal:'Consolidar as quatro habilidades anteriores.',kind:'readiness'},
'2-0':{title:'A sensação de casa',theory:'Em uma tonalidade, algumas notas criam movimento e outra transmite repouso. Essa sensação de casa é a pista central.',goal:'Encontrar a nota de repouso.',kind:'tonic'},
'2-1':{title:'Encontrando a tônica',theory:'A primeira nota de uma música não precisa ser a tônica. A tônica é o centro para o qual a música parece querer voltar.',goal:'Separar nota inicial de centro tonal.',kind:'tonic'},
'2-2':{title:'Graus da escala',theory:'Quando organizamos a escala a partir da tônica, cada posição recebe um grau. O ouvido pode aprender essas relações antes da teoria escrita.',goal:'Reconhecer movimentos relativos à tônica.',kind:'degrees'},
'2-3':{title:'I–IV–V na prática',theory:'Tônica, subdominante e dominante formam uma das bases mais úteis da harmonia tonal.',goal:'Ouvir repouso, afastamento e retorno.',kind:'progression'},
'2-4':{title:'Teste de tonalidade',theory:'Agora você precisa localizar o centro sem depender da primeira nota.',goal:'Encontrar a tônica de um pequeno trecho.',kind:'tonic'},
'3-0':{title:'Passos e saltos',theory:'Movimento conjunto usa notas próximas; saltos atravessam uma distância maior. Essa diferença forma o desenho da melodia.',goal:'Distinguir passo de salto.',kind:'interval'},
'3-1':{title:'Quanto distante?',theory:'Intervalo é a distância entre duas alturas. Primeiro percebemos pequeno/médio/grande; depois damos o nome.',goal:'Comparar distâncias.',kind:'interval'},
'3-2':{title:'Contorno melódico',theory:'Contorno é o desenho geral da melodia: sobe, desce, repete e salta.',goal:'Reconhecer a forma sem precisar nomear todas as notas.',kind:'contour'},
'3-3':{title:'Eco melódico',theory:'Ouvir e cantar de volta transforma percepção em memória ativa. Começamos com frases curtas.',goal:'Reproduzir uma pequena frase.',kind:'echo'},
'3-4':{title:'Ditado auditivo',theory:'Ditado é transformar som em informação consciente. O objetivo é ouvir relações, não adivinhar.',goal:'Identificar a sequência relativa.',kind:'dictation'},
'4-0':{title:'Ouvindo um acorde',theory:'Acorde é um conjunto de notas soando em conjunto. Primeiro reconheça a textura; depois investigue sua qualidade.',goal:'Distinguir sons harmônicos.',kind:'chord'},
'4-1':{title:'Maior ou menor?',theory:'A terça é a pista decisiva: em Dó maior temos Dó–Mi–Sol; em Dó menor, Dó–Mi♭–Sol.',goal:'Distinguir maior de menor.',kind:'majorMinor'},
'4-2':{title:'Ouvindo o baixo',theory:'A nota mais grave ajuda a revelar a base do acorde e suas inversões.',goal:'Perceber qual nota está no baixo.',kind:'bass'},
'4-3':{title:'I–IV–V',theory:'Funções harmônicas criam direção: a tônica repousa, a dominante pede resolução.',goal:'Reconhecer a função pela sensação.',kind:'progression'},
'4-4':{title:'Progressões',theory:'Depois de ouvir funções isoladas, podemos acompanhar uma sequência e prever seu próximo movimento.',goal:'Identificar padrões harmônicos.',kind:'progression'},
'5-0':{title:'Encontrar o repouso',theory:'Ao descobrir o tom de uma música, procure a nota que parece completar a frase e funcionar como casa.',goal:'Encontrar o centro tonal.',kind:'tonic'},
'5-1':{title:'Maior ou menor na música',theory:'O modo muda o caráter da tonalidade. A terça e os acordes são pistas úteis.',goal:'Classificar maior ou menor.',kind:'majorMinor'},
'5-2':{title:'O cantor começa fora da tônica',theory:'Uma voz pode começar no 3º, 5º ou outro grau. Nunca conclua o tom somente pela primeira nota.',goal:'Encontrar a tônica depois de uma nota inicial diferente.',kind:'singer'},
'5-3':{title:'Transposição e capo',theory:'Depois de descobrir o tom, você pode mover a música para outra tonalidade e usar o capo para manter desenhos de acordes.',goal:'Relacionar ouvido, tom e braço do violão.',kind:'transpose'},
'5-4':{title:'Desafio de música',theory:'Agora reunimos centro tonal, modo e aplicação no violão em uma situação musical.',goal:'Resolver uma descoberta completa.',kind:'singer'},
'6-0':{title:'Diagnóstico inicial',theory:'Um bom diagnóstico não pergunta apenas se você terminou: mede o que consegue reconhecer.',goal:'Mapear suas forças e fraquezas.',kind:'diagnostic'},
'6-1':{title:'Teste de notas',theory:'Mede a ligação entre altura ouvida e nome da nota.',goal:'Avaliar reconhecimento.',kind:'note'},
'6-2':{title:'Teste de tonalidade',theory:'Mede sua capacidade de encontrar a casa da música.',goal:'Avaliar centro tonal.',kind:'tonic'},
'6-3':{title:'Teste de harmonia',theory:'Mede qualidade de acordes e sensação de função.',goal:'Avaliar harmonia.',kind:'majorMinor'},
'6-4':{title:'Desafio final',theory:'A prova final integra percepção, tonalidade e aplicação musical.',goal:'Demonstrar transferência para uma situação real.',kind:'final'}
};
function lessonPage(mid,li){const m=MODULES.find(x=>x.id===mid),key=mid+'-'+li,L=LESSONS[key]||LESSONS['1-0'];current={m:mid,l:li};route='lesson';render(`<section class="hero"><span class="eyebrow">Módulo ${mid} • Aula ${li+1}</span><h1>${L.title}</h1><p>${L.goal}</p></section><article class="card"><h2>📖 Entenda</h2><p>${L.theory}</p><div class="callout"><b>Regra de ouro:</b> não tente decorar uma resposta. Pergunte ao seu ouvido: “o que mudou?”, “para onde foi?” ou “onde repousou?”.</div></article><article class="card"><h2>🎧 Experiência guiada</h2><p>Ouça primeiro. A pergunta aparece depois para evitar que você responda apenas pela leitura.</p><div id="exercise"></div></article><div class="row"><button class="btn alt" data-module="${mid}">← Trilha</button><button class="btn" data-next="${mid}-${li}">Próxima aula →</button></div>`);exercise(L.kind,mid,li)}
function buttons(items){return `<div class="choices">${items.map(x=>`<button class="choice" data-answer="${esc(x.v)}" data-correct="${esc(x.c)}">${x.t}</button>`).join('')}</div><div id="efb"></div>`}
function exercise(kind,mid,li){const box=document.getElementById('exercise');if(!box)return;let h='';if(kind==='height'){const a='C',b='G';h=`<button class="listen" onclick="play(['${a}','${b}'])">▶ Ouvir A → B</button>${buttons([{v:'A',c:'B',t:'A é mais agudo'},{v:'B',c:'B',t:'B é mais agudo'}])}`}
else if(kind==='same'){h=`<button class="listen" onclick="play(['E','E'])">▶ Ouvir</button>${buttons([{v:'igual',c:'igual',t:'São iguais'},{v:'diferente',c:'igual',t:'São diferentes'}])}`}
else if(kind==='direction'){h=`<button class="listen" onclick="play(['C','E'])">▶ Ouvir</button>${buttons([{v:'subiu',c:'subiu',t:'Subiu'},{v:'desceu',c:'subiu',t:'Desceu'},{v:'repetiu',c:'subiu',t:'Repetiu'}])}`}
else if(kind==='note'){const n='C';h=`<button class="listen" onclick="play(['${n}'])">▶ Ouvir a nota</button>${buttons(NOTES.slice(0,4).map(x=>({v:x,c:n,t:N[x]})))}`}
else if(kind==='majorMinor'){h=`<div class="row"><button class="btn" onclick="play(['C','E','G'])">▶ Acorde A</button><button class="btn alt" onclick="play(['C','Eb','G'])">▶ Acorde B</button></div>${buttons([{v:'maior',c:'maior',t:'A é maior'},{v:'menor',c:'maior',t:'A é menor'}])}`}
else if(kind==='tonic'||kind==='singer'){h=`<button class="listen" onclick="play(['E','G','C'])">▶ Ouvir frase</button><p>Qual nota soa como casa?</p>${buttons(NOTES.slice(0,4).map(x=>({v:x,c:'C',t:N[x]})))}`}
else if(kind==='contour'){h=`<button class="listen" onclick="play(['C','E','D','G'])">▶ Ouvir melodia</button>${buttons([{v:'↑ ↓ ↑',c:'↑ ↑ ↓',t:'Sobe, desce, sobe'},{v:'↑ ↑ ↓',c:'↑ ↑ ↓',t:'Sobe, sobe, desce'},{v:'↓ ↓ ↑',c:'↑ ↑ ↓',t:'Desce, desce, sobe'}])}`}
else if(kind==='interval'){h=`<button class="listen" onclick="play(['C','D'])">▶ Intervalo A</button><div class="row"><button class="btn alt" onclick="play(['C','G'])">▶ Intervalo B</button></div>${buttons([{v:'menor',c:'menor',t:'A é menor'},{v:'maior',c:'menor',t:'A é maior'}])}`}
else if(kind==='progression'||kind==='bass'){h=`<button class="listen" onclick="play(['C','F','G','C'])">▶ Ouvir progressão</button>${buttons([{v:'repouso',c:'repouso',t:'Termina em repouso'},{v:'tensao',c:'repouso',t:'Termina em tensão'}])}`}
else if(kind==='echo'||kind==='dictation'){h=`<button class="listen" onclick="play(['C','D','E'])">▶ Ouvir frase</button><p>Depois de ouvir, qual foi o desenho?</p>${buttons([{v:'↑ ↑',c:'↑ ↑',t:'Subiu e subiu'},{v:'↓ ↑',c:'↑ ↑',t:'Desceu e subiu'},{v:'↑ ↓',c:'↑ ↑',t:'Subiu e desceu'}])}`}
else if(kind==='transpose'){h=`<div class="callout">Imagine que uma música está em Dó e você precisa tocar em Ré. O que aconteceu?</div>${buttons([{v:'subiu',c:'subiu',t:'A tonalidade subiu'},{v:'desceu',c:'subiu',t:'A tonalidade desceu'},{v:'igual',c:'subiu',t:'Nada mudou'}])}`}
else {h=`<div class="callout">Faça primeiro o exercício de ouvido abaixo e use o resultado para orientar o próximo treino.</div><button class="listen" onclick="play(['C','E','G','C'])">▶ Ouvir desafio</button>${buttons([{v:'C',c:'C',t:'Minha resposta: Dó'},{v:'G',c:'C',t:'Minha resposta: Sol'},{v:'E',c:'C',t:'Minha resposta: Mi'}])}`}
box.innerHTML=h;box.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(b,b.dataset.answer,b.dataset.correct,mid,li)))}
function answer(btn,a,c,mid,li){const good=a===c;state.attempts++;if(good){state.correct++;state.xp+=10;state.streak++;state.level=Math.min(10,state.level+1)}else{state.streak=0;state.level=Math.max(1,state.level-1)}const skill=skillFor(mid);state.skills[skill]=Math.max(0,Math.min(100,state.skills[skill]+(good?8:-5)));state.lessons[mid+'-'+li]=good?'done':'review';document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);const f=document.getElementById('efb');if(f)f.innerHTML=`<div class="feedback ${good?'ok':'no'}"><b>${good?'✓ Muito bem!':'↺ Vamos reforçar'}</b><br>${good?'Você identificou a relação pedida.':'A resposta esperada é <b>'+esc(c)+'</b>. Ouça novamente e tente explicar o que mudou.'}</div>`;save()}
function skillFor(id){return id===1?'note':id===2?'tonic':id===3?'interval':id===4?'chord':'song'}
function memory(){route='memory';render(`<section class="hero"><span class="eyebrow">Memória auditiva</span><h1>🧠 Ouça. Silencie. Recupere.</h1><p>Treine a capacidade de manter uma informação sonora enquanto ela não está mais tocando.</p></section><div class="grid"><article class="card"><h3>Nota</h3><p>Memorize uma altura.</p><button class="btn" onclick="memoryNote()">Começar</button></article><article class="card"><h3>Sequência</h3><p>Memorize uma pequena frase.</p><button class="btn" onclick="memorySeq()">Começar</button></article><article class="card"><h3>Contorno</h3><p>Memorize apenas a direção.</p><button class="btn" onclick="memoryContour()">Começar</button></article></div><div id="mem"></div>`)}
function memoryUI(title,a,opts,c){const box=document.getElementById('mem');box.innerHTML=`<article class="card"><span class="eyebrow">${title}</span><div class="memory"><strong>🎧</strong><p>Ouça, desvie o olhar das opções e recupere o som.</p><button class="listen" onclick="play(${JSON.stringify(a)})">▶ Ouvir</button></div>${buttons(opts.map(x=>({v:x,c,t:x})))}</article>`;box.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerMemory(b,b.dataset.answer,b.dataset.correct)))}
function memoryNote(){const c='Dó';memoryUI('Memória de uma nota',['C'],['Dó','Ré','Mi','Sol'],c)}
function memorySeq(){const a=['C','E','G'],c='Dó → Mi → Sol';memoryUI('Memória de sequência',a,[c,'Sol → Mi → Dó','Dó → Ré → Sol','Mi → Sol → Dó'],c)}
function memoryContour(){const a=['C','E','D'],c='↑ ↑ ↓';memoryUI('Memória de contorno',a,['↑ ↑ ↓','↓ ↑ ↑','↑ ↓ ↑','↓ ↓ ↓'],c)}
function answerMemory(btn,a,c){const good=a===c;state.attempts++;if(good){state.correct++;state.xp+=10;state.streak++;}else state.streak=0;document.querySelectorAll('#mem [data-answer]').forEach(x=>x.disabled=true);document.getElementById('efb').innerHTML=`<div class="feedback ${good?'ok':'no'}"><b>${good?'✓ Correto':'↺ Reforce'}</b><br>${good?'Sua memória recuperou a informação.':'A resposta era <b>'+esc(c)+'</b>. Ouça mais uma vez.'}</div>`;save()}
function apply(){route='apply';render(`<section class="hero"><span class="eyebrow">Aplicação musical</span><h1>👂 Ouvido → 🎸 música</h1><p>A teoria começa a fazer sentido quando você consegue usá-la.</p></section><article class="card"><h2>Maior × menor</h2><p>Compare a terça.</p><div class="row"><button class="btn" onclick="play(['C','E','G'])">▶ C maior</button><button class="btn alt" onclick="play(['C','Eb','G'])">▶ C menor</button></div></article><article class="card"><h2>🎤 Primeira nota não é necessariamente a tônica</h2><p>O centro tonal é encontrado pela sensação de repouso.</p><button class="btn" onclick="startSinger()">🎧 Simular trecho</button><div id="challenge"></div></article>`)}
function startSinger(){const box=document.getElementById('challenge');box.innerHTML=`<div class="callout"><button class="listen" onclick="play(['E','G','C','G','E'])">▶ Ouvir trecho</button><p>O cantor começa em <b>Mi</b>, mas a frase repousa em outra nota.</p>${buttons(NOTES.slice(0,4).map(x=>({v:x,c:'C',t:N[x]})))}</div>`;box.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const good=b.dataset.answer===b.dataset.correct;state.attempts++;if(good){state.correct++;state.xp+=15;state.streak++}else state.streak=0;box.insertAdjacentHTML('beforeend',`<div class="feedback ${good?'ok':'no'}">${good?'✓ Você separou nota inicial de tônica.':'↺ A tônica era Dó. Procure o repouso.'}</div>`);save()}))}
function guitar(){route='guitar';render(`<section class="hero"><span class="eyebrow">Laboratório de violão</span><h1>🎸 Ouça e encontre no braço.</h1><p>Afinação padrão: E–A–D–G–B–E. Sem teclado: aqui o instrumento é o violão.</p></section><article class="card"><h2>Alvo auditivo</h2><div class="row">${NOTES.map(n=>`<button class="btn" onclick="tone('${n}');document.getElementById('target').textContent='Alvo: '+N[n]">${N[n]}</button>`).join('')}</div><div id="target" class="callout">Escolha um alvo.</div></article><article class="card"><h2>Mapa inicial do braço</h2><div class="neck">${['E','A','D','G','B','E'].map(s=>`<div class="string"><b>${s}</b>${[0,1,2,3,5,7,9,12].map(f=>`<span class="fret">${f}</span>`).join('')}</div>`).join('')}</div><p class="mini">Próxima evolução: transformar cada casa em alvo clicável e verificar automaticamente a nota encontrada.</p></article>`)}
function diagnostics(){route='diagnostic';const skills=[['note','Notas'],['tonic','Tonalidade'],['interval','Intervalos'],['chord','Harmonia'],['song','Músicas']];render(`<section class="hero"><span class="eyebrow">Diagnóstico</span><h1>🏆 Seu mapa auditivo</h1><p>Não olhamos só para quantidade. Olhamos para desempenho.</p></section><div class="card"><div class="stats"><div class="stat"><b>${acc()}%</b><small>precisão geral</small></div><div class="stat"><b>${state.xp}</b><small>XP</small></div><div class="stat"><b>${state.level}</b><small>nível</small></div></div><h2 style="margin-top:18px">Habilidades</h2>${skills.map(x=>`<div class="callout"><b>${x[1]}</b><br>${state.skills[x[0]]}% de domínio</div>`).join('')}<div class="callout gold"><b>Próximo foco:</b> ${nextSkill(skills)}</div></div>`)}
function nextSkill(skills){let s=skills.slice().sort((a,b)=>state.skills[a[0]]-state.skills[b[0]])[0];return s[1]+' — faça mais uma aula antes de avançar.'}
function bind(){document.addEventListener('click',e=>{const r=e.target.closest('[data-route]'),m=e.target.closest('[data-module]'),l=e.target.closest('[data-lesson]'),nx=e.target.closest('[data-next]');if(r){const x=r.dataset.route;({home,modules,memory,apply,guitar,diagnostics}[x]||home)();return}if(m){modulePage(Number(m.dataset.module));return}if(l){const [a,b]=l.dataset.lesson.split('-').map(Number);lessonPage(a,b);return}if(nx){const [a,b]=nx.dataset.next.split('-').map(Number),m2=MODULES.find(x=>x.id===a);if(m2&&b+1<m2.lessons.length)lessonPage(a,b+1);else modulePage(a)}})}
window.play=play;window.tone=tone;window.memoryNote=memoryNote;window.memorySeq=memorySeq;window.memoryContour=memoryContour;window.startSinger=startSinger;bind();
window.addEventListener('error',e=>{const app=document.getElementById('app');if(app&&!app.innerHTML.trim())app.innerHTML='<div class="card"><h2>Ocorreu um erro ao carregar esta tela.</h2><p>Tente recarregar a página. Se persistir, envie esta mensagem para o suporte.</p></div>'});
home();
})();