(function(){
'use strict';
const N=window.NOTES||['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const NN=window.NOTE_NAMES||['Dó','Dó♯','Ré','Mi♭','Mi','Fá','Fá♯','Sol','Lá♭','Lá','Si♭','Si'];
const FALLBACK_FREQ={C:261.626,'C#':277.183,D:293.665,Eb:311.127,E:329.628,F:349.228,'F#':369.994,G:391.995,Ab:415.305,A:440,Bb:466.164,B:493.883};
const KEY='pm_memory_v3';
let mode='free',target='C',oct=4,reps=0,tests=[],q=0,score=0,level='ref',session={correct:0,total:0};
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
let mem=load();
mem.notes=mem.notes||{};N.forEach(n=>mem.notes[n]=mem.notes[n]||{ok:0,total:0});
mem.sessions=mem.sessions||0;mem.best=mem.best||0;
function save(){localStorage.setItem(KEY,JSON.stringify(mem))}
function pct(n){let s=mem.notes[n];return s&&s.total?Math.round(s.ok/s.total*100):0}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function shuffle(a){return a.slice().sort(()=>Math.random()-.5)}
function freq(n){return (FALLBACK_FREQ[n]||261.626)*Math.pow(2,oct-4)}
function play(n,d=.72,delay=0){if(typeof window.beep==='function'){setTimeout(()=>window.beep(n,d,0,'instrument',oct),delay);return}let C=window.audioCtx||(window.audioCtx=new(window.AudioContext||window.webkitAudioContext)());if(C.state==='suspended')C.resume();let o=C.createOscillator(),g=C.createGain();o.type='triangle';o.frequency.value=freq(n);g.gain.setValueAtTime(.0001,C.currentTime+delay/1000);g.gain.exponentialRampToValueAtTime(.24,C.currentTime+delay/1000+.025);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+delay/1000+d);o.connect(g).connect(C.destination);o.start(C.currentTime+delay/1000);o.stop(C.currentTime+delay/1000+d+.03)}
function playRefAndTarget(t,l){let i=N.indexOf(t),ref=N[(i+7)%12];if(l==='ref'){play(ref,.55);play(t,.72,700)}else if(l==='delay'){play(ref,.55);play(t,.72,1500)}else play(t,.72)}
const CSS=`#pmMemBtn{position:fixed;right:14px;bottom:18px;z-index:9998;border:0;border-radius:999px;padding:12px 16px;background:#0f172a;color:#fff;font-weight:850;box-shadow:0 6px 20px #0004}#pmMem{position:fixed;inset:0;background:#0f172acc;z-index:9999;display:none;padding:12px;overflow:auto;font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial}#pmBox{max-width:760px;margin:12px auto 40px;background:#fff;border-radius:22px;padding:18px;color:#172033;box-shadow:0 18px 50px #0005}.pmTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.pmTop h2{margin:0 0 5px}.pmClose{border:0;background:#fee2e2;color:#991b1b;border-radius:10px;padding:8px 10px;font-weight:800}.pmTabs,.pmRow{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.pmTabs{margin:15px 0}.pmTab,.pmBtn{border:0;border-radius:11px;padding:10px 13px;font-weight:800}.pmTab{background:#e8eef8;color:#172033}.pmTab.on,.pmBtn{background:#2563eb;color:#fff}.pmGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.pmGrid button{border:1px solid #d8e0eb;background:#fff;border-radius:10px;padding:10px 6px;font-weight:750;min-height:43px}.pmGrid button:hover{border-color:#2563eb;background:#eff6ff}.pmGrid button:disabled{opacity:.65}.pmMuted{color:#64748b;line-height:1.5}.pmPanel{background:#f8fafc;border:1px solid #e2e8f0;border-radius:15px;padding:13px;margin-top:12px}.pmGood{background:#dcfce7;color:#166534}.pmBad{background:#fee2e2;color:#991b1b}.pmRes{padding:12px;border-radius:12px;margin-top:12px}.pmStatGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.pmStat{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:10px}.pmStat b{display:block;font-size:20px}.pmNote{display:flex;align-items:center;gap:8px;margin:7px 0}.pmNote span:first-child{width:48px;font-weight:800}.pmBar{height:8px;flex:1;background:#e2e8f0;border-radius:99px;overflow:hidden}.pmBar i{display:block;height:100%;background:#2563eb}.pmWeak{background:#fff7ed;border-left:4px solid #d97706;padding:10px 12px;border-radius:9px;margin-top:10px}.pmHint{background:#eff6ff;border-left:4px solid #2563eb;padding:10px 12px;border-radius:9px;margin:10px 0}@media(max-width:520px){.pmGrid{grid-template-columns:repeat(3,1fr)}.pmStatGrid{grid-template-columns:1fr 1fr}.pmBox{padding:14px}}`;
function ui(){if(document.getElementById('pmMemBtn'))return;let st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);let b=document.createElement('button');b.id='pmMemBtn';b.textContent='🧠 Memorização';b.onclick=()=>{document.getElementById('pmMem').style.display='block';render()};document.body.appendChild(b);let o=document.createElement('div');o.id='pmMem';o.innerHTML='<div id="pmBox"><div class="pmTop"><div><h2>🧠 Memorização das notas</h2><div class="pmMuted">Treine a sonoridade antes de tentar acertar rápido. O objetivo é criar uma referência interna.</div></div><button class="pmClose" id="pmClose">Fechar</button></div><div class="pmTabs"><button class="pmTab on" id="tabF">🎧 Treino livre</button><button class="pmTab" id="tabT">📝 Teste</button><button class="pmTab" id="tabP">📊 Progresso</button></div><div id="pmContent"></div></div>';document.body.appendChild(o);document.getElementById('pmClose').onclick=()=>o.style.display='none';document.getElementById('tabF').onclick=()=>switchMode('free');document.getElementById('tabT').onclick=()=>switchMode('test');document.getElementById('tabP').onclick=()=>switchMode('progress')}
function switchMode(m){mode=m;tests=[];q=0;score=0;['tabF','tabT','tabP'].forEach(id=>document.getElementById(id).classList.remove('on'));document.getElementById(m==='free'?'tabF':m==='test'?'tabT':'tabP').classList.add('on');render()}
function render(){let c=document.getElementById('pmContent');if(!c)return;if(mode==='free')return free(c);if(mode==='progress')return progress(c);test(c)}
function free(c){let ti=NN[N.indexOf(target)];c.innerHTML='<div class="pmPanel"><div class="pmRow"><b>1. Escolha uma nota</b><span class="pmMuted">Depois de escolher, não fique trocando: repita até a sonoridade ficar familiar.</span></div><div class="pmGrid">'+N.map((x,i)=>'<button data-n="'+x+'" class="'+(x===target?'on':'')+'">'+NN[i]+'</button>').join('')+'</div><div class="pmRow"><button class="pmBtn" id="pmPlay">🔊 Ouvir '+ti+'</button><button class="pmTab" id="pmRep">🔁 Repetir 3x</button><button class="pmTab" id="pmZero">Zerar repetições</button></div><div class="pmRow" style="margin-top:10px"><b>Oitava:</b><button class="pmTab" id="octDown">−</button><span><b>'+oct+'</b></span><button class="pmTab" id="octUp">+</button><span class="pmMuted">A oitava muda a altura, não o nome da nota.</span></div></div><div class="pmHint"><b>Como estudar:</b> ouça → pare o som → imagine a nota → cante mentalmente → ouça novamente e confira. Não tente decorar apenas pelo timbre do instrumento.</div><div class="pmPanel"><b>Repetições nesta sessão:</b> '+reps+'<br><span class="pmMuted">Próximo passo: quando reconhecer a nota sem olhar, vá para o teste sem referência.</span></div>';c.querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>{target=x.dataset.n;reps=0;render();play(target)});document.getElementById('pmPlay').onclick=()=>{play(target);reps++;render()};document.getElementById('pmRep').onclick=()=>{[0,700,1400].forEach(d=>play(target,.65,d));reps+=3;render()};document.getElementById('pmZero').onclick=()=>{reps=0;render()};document.getElementById('octDown').onclick=()=>{oct=Math.max(2,oct-1);render()};document.getElementById('octUp').onclick=()=>{oct=Math.min(6,oct+1);render()}}
function weakest(){return N.map(n=>({n,p:pct(n),t:mem.notes[n].total})).sort((a,b)=>a.p-b.p||a.t-b.t)}
function progress(c){let total=N.reduce((a,n)=>a+mem.notes[n].total,0),ok=N.reduce((a,n)=>a+mem.notes[n].ok,0),avg=total?Math.round(ok/total*100):0,w=weakest().slice(0,3);c.innerHTML='<div class="pmStatGrid"><div class="pmStat"><span class="pmMuted">Acerto geral</span><b>'+avg+'%</b></div><div class="pmStat"><span class="pmMuted">Questões</span><b>'+total+'</b></div><div class="pmStat"><span class="pmMuted">Melhor teste</span><b>'+mem.best+'%</b></div></div><div class="pmPanel"><b>Memória por nota</b>'+N.map(n=>'<div class="pmNote"><span>'+NN[N.indexOf(n)]+'</span><div class="pmBar"><i style="width:'+pct(n)+'%"></i></div><small>'+pct(n)+'% ('+mem.notes[n].ok+'/'+mem.notes[n].total+')</small></div>').join('')+'</div><div class="pmWeak"><b>🎯 Próximo reforço:</b> '+w.map(x=>NN[N.indexOf(x.n)]).join(', ')+'. '+(total?'Treine primeiro a nota com menor precisão.':'Faça o primeiro teste para criar seu diagnóstico.')+'</div><div class="pmRow" style="margin-top:12px"><button class="pmBtn" id="weakTest">Treinar notas fracas</button><button class="pmTab" id="resetMem">Zerar diagnóstico</button></div>';document.getElementById('weakTest').onclick=()=>{start('none',true)};document.getElementById('resetMem').onclick=()=>{if(confirm('Zerar apenas o diagnóstico de memorização?')){mem={notes:{},sessions:0,best:0};N.forEach(n=>mem.notes[n]={ok:0,total:0});save();render()}}}
function start(l,weak=false){level=l;let pool=weak?weakest().slice(0,5).map(x=>x.n):N;tests=Array.from({length:15},()=>({t:pool[Math.floor(Math.random()*pool.length)],l}));q=score=0;session={correct:0,total:0};mode='test';document.getElementById('tabF').classList.remove('on');document.getElementById('tabP').classList.remove('on');document.getElementById('tabT').classList.add('on');render()}
function test(c){if(!tests.length){c.innerHTML='<div class="pmPanel"><b>Teste de memorização</b><p class="pmMuted">15 questões. Todas as 12 notas aparecem como alternativas. Primeiro construa a referência; depois retire a ajuda.</p><div class="pmRow"><button class="pmBtn" data-l="ref">🎧 Com referência</button><button class="pmTab" data-l="delay">⏳ Referência atrasada</button><button class="pmTab" data-l="none">🧠 Sem referência</button></div><div class="pmHint"><b>Regra:</b> se estiver chutando, volte um nível. O objetivo é reconhecer a nota, não acertar por sorte.</div></div><div class="pmPanel"><b>Seu diagnóstico atual</b><p class="pmMuted">Acerto geral: '+overall()+'%. As notas mais fracas são: '+weakest().slice(0,3).map(x=>NN[N.indexOf(x.n)]+' '+x.p+'%').join(' · ')+'</p></div>';c.querySelectorAll('[data-l]').forEach(x=>x.onclick=()=>start(x.dataset.l));return}if(q>=tests.length){finish(c);return}let t=tests[q];c.innerHTML='<div class="pmRow"><b>Questão '+(q+1)+'/15</b><span class="pmMuted">Acertos: '+score+'</span></div><div class="pmHint">'+(t.l==='ref'?'Uma referência será tocada antes da nota-alvo.':t.l==='delay'?'A referência será tocada e haverá uma pausa antes da nota-alvo.':'Não haverá referência externa. Confie na memória auditiva.')+'</div><button class="pmBtn" id="qplay">🔊 Ouvir</button><div class="pmGrid">'+N.map((x,i)=>'<button data-a="'+x+'">'+NN[i]+'</button>').join('')+'</div><div id="qr"></div>';document.getElementById('qplay').onclick=()=>playRefAndTarget(t.t,t.l);c.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>answer(x.dataset.a));setTimeout(()=>playRefAndTarget(t.t,t.l),180)}
function overall(){let t=N.reduce((a,n)=>a+mem.notes[n].total,0),o=N.reduce((a,n)=>a+mem.notes[n].ok,0);return t?Math.round(o/t*100):0}
function answer(a){let t=tests[q],ok=a===t.t;mem.notes[t.t].total++;if(ok){score++;mem.notes[t.t].ok++}save();document.querySelectorAll('[data-a]').forEach(x=>x.disabled=true);document.getElementById('qr').innerHTML='<div class="pmRes '+(ok?'pmGood':'pmBad')+'"><b>'+(ok?'✅ Correto!':'❌ Ainda não.')+'</b><br>Resposta: <b>'+esc(NN[N.indexOf(t.t)])+'</b>'+(ok?'':'<br><span>Ouça novamente e tente cantar a nota-alvo antes de passar.</span>')+'</div>';setTimeout(()=>{q++;render()},850)}
function finish(c){let p=Math.round(score/tests.length*100);mem.sessions++;if(p>mem.best)mem.best=p;save();let weak=weakest().slice(0,3);c.innerHTML='<div class="pmRes '+(p>=85?'pmGood':p>=70?'':'pmBad')+'"><b>🏁 Teste concluído</b><p>Resultado: <b>'+score+'/'+tests.length+'</b> ('+p+'%).</p><p>'+(p>=85?'Excelente. Você pode reduzir a dependência de referência.':p>=70?'Boa base. Reforce as notas que mais errar antes de aumentar a dificuldade.':'Ainda há muita dependência de referência. Volte ao treino livre e trabalhe as notas mais fracas.')+'</p></div><div class="pmPanel"><b>Notas que merecem reforço</b><p class="pmMuted">'+weak.map(x=>NN[N.indexOf(x.n)]+' — '+x.p+'%').join(' · ')+'</p></div><div class="pmRow"><button class="pmBtn" id="again">Novo teste</button><button class="pmTab" id="goProgress">Ver progresso</button></div>';document.getElementById('again').onclick=()=>{tests=[];q=score=0;render()};document.getElementById('goProgress').onclick=()=>switchMode('progress')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();