(function(){
const N=window.NOTES||['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const NN=window.NOTE_NAMES||['Dó','Dó♯','Ré','Mi♭','Mi','Fá','Fá♯','Sol','Lá♭','Lá','Si♭','Si'];
let mode='free',target='C',tests=[],q=0,score=0,reps=0;
const S=`#pmMemBtn{position:fixed;right:14px;bottom:18px;z-index:9998;border:0;border-radius:999px;padding:12px 16px;background:#0f172a;color:#fff;font-weight:800;box-shadow:0 6px 20px #0004}#pmMem{position:fixed;inset:0;background:#0f172acc;z-index:9999;display:none;padding:16px;overflow:auto;font-family:system-ui}#pmBox{max-width:700px;margin:25px auto;background:#fff;border-radius:22px;padding:18px;color:#172033}.pmTabs,.pmRow{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.pmTabs{margin:14px 0}.pmTab,.pmBtn{border:0;border-radius:11px;padding:10px 13px;font-weight:800}.pmTab{background:#e8eef8}.pmTab.on,.pmBtn{background:#2563eb;color:#fff}.pmClose{float:right;border:0;background:#fee2e2;color:#991b1b;border-radius:9px;padding:7px}.pmGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.pmGrid button{border:1px solid #d8e0eb;background:#fff;border-radius:10px;padding:10px;font-weight:700}.pmGood{background:#dcfce7;color:#166534}.pmBad{background:#fee2e2;color:#991b1b}.pmRes{padding:12px;border-radius:12px;margin-top:12px}.pmMuted{color:#64748b;line-height:1.5}`;
function beep2(n,d=.7){if(window.beep){window.beep(n,d);return}let C=window.audioCtx||(window.audioCtx=new(window.AudioContext||window.webkitAudioContext)()),o=C.createOscillator(),g=C.createGain();o.type='triangle';o.frequency.value=({C:261.626,'C#':277.183,D:293.665,Eb:311.127,E:329.628,F:349.228,'F#':369.994,G:391.995,Ab:415.305,A:440,Bb:466.164,B:493.883})[n];g.gain.value=.2;o.connect(g).connect(C.destination);o.start();o.stop(C.currentTime+d)}
function ui(){if(document.getElementById('pmMemBtn'))return;let st=document.createElement('style');st.textContent=S;document.head.appendChild(st);let b=document.createElement('button');b.id='pmMemBtn';b.textContent='🧠 Memorização';b.onclick=()=>{document.getElementById('pmMem').style.display='block';render()};document.body.appendChild(b);let o=document.createElement('div');o.id='pmMem';o.innerHTML='<div id="pmBox"><button class="pmClose" onclick="document.getElementById(\'pmMem\').style.display=\'none\'">Fechar</button><h2>🧠 Memorização das notas</h2><p class="pmMuted">Treine a sonoridade e teste sua memória. O teste oferece sempre as 12 notas.</p><div class="pmTabs"><button class="pmTab on" id="tabF">🎧 Treino livre</button><button class="pmTab" id="tabT">📝 Teste</button></div><div id="pmContent"></div></div>';document.body.appendChild(o);document.getElementById('tabF').onclick=()=>{mode='free';tests=[];document.getElementById('tabF').classList.add('on');document.getElementById('tabT').classList.remove('on');render()};document.getElementById('tabT').onclick=()=>{mode='test';document.getElementById('tabT').classList.add('on');document.getElementById('tabF').classList.remove('on');render()}}
function render(){let c=document.getElementById('pmContent');if(!c)return;if(mode==='free'){c.innerHTML='<div class="pmRow"><b>Treino livre</b><span class="pmMuted">Repetições: '+reps+'</span></div><p class="pmMuted">Escolha uma nota, ouça, cante mentalmente e repita.</p><div class="pmGrid">'+N.map((x,i)=>'<button data-n="'+x+'">'+NN[i]+'</button>').join('')+'</div><div class="pmRow"><button class="pmBtn" id="pmPlay">🔊 Ouvir '+NN[N.indexOf(target)]+'</button><button class="pmTab" id="pmRep">🔁 Repetir</button><button class="pmTab" id="pmZero">Zerar</button></div><div class="pmRes pmGood">Nota: <b>'+NN[N.indexOf(target)]+'</b> — objetivo: ouvir → cantar → reconhecer.</div>';c.querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>{target=x.dataset.n;reps=0;render();beep2(target)});document.getElementById('pmPlay').onclick=()=>{beep2(target);reps++;render()};document.getElementById('pmRep').onclick=()=>{beep2(target);reps++};document.getElementById('pmZero').onclick=()=>{reps=0;render()};return}if(!tests.length){c.innerHTML='<div class="pmRes"><b>Teste de memorização — 15 questões</b><p class="pmMuted">Escolha o nível. Todas as 12 notas serão alternativas.</p><div class="pmRow"><button class="pmBtn" data-l="ref">Com referência</button><button class="pmTab" data-l="delay">Referência atrasada</button><button class="pmTab" data-l="none">Sem referência</button></div></div>';c.querySelectorAll('[data-l]').forEach(x=>x.onclick=()=>start(x.dataset.l));return}if(q>=tests.length){c.innerHTML='<div class="pmRes pmGood"><b>🏁 Concluído!</b><p>Resultado: <b>'+score+'/'+tests.length+'</b> ('+Math.round(score/tests.length*100)+'%).</p><button class="pmBtn" id="newT">Novo teste</button></div>';document.getElementById('newT').onclick=()=>{tests=[];q=score=0;render()};return}let t=tests[q];c.innerHTML='<div class="pmRow"><b>Questão '+(q+1)+'/15</b><span>Acertos: '+score+'</span></div><p class="pmMuted">'+(t.l==='ref'?'Referência antes do alvo.':t.l==='delay'?'Referência, pausa e alvo.':'Sem referência.')+'</p><button class="pmBtn" id="qplay">🔊 Ouvir</button><div class="pmGrid">'+N.map((x,i)=>'<button data-a="'+x+'">'+NN[i]+'</button>').join('')+'</div><div id="qr"></div>';document.getElementById('qplay').onclick=playQ;c.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>answer(x.dataset.a));setTimeout(playQ,150)}
function start(l){tests=Array.from({length:15},()=>({t:N[Math.floor(Math.random()*12)],l}));q=score=0;render();}
function playQ(){let t=tests[q],i=N.indexOf(t.t),ref=N[(i+7)%12];if(t.l==='ref'){beep2(ref,.6);setTimeout(()=>beep2(t.t,.75),700)}else if(t.l==='delay'){beep2(ref,.6);setTimeout(()=>beep2(t.t,.75),1300)}else beep2(t.t,.75)}
function answer(a){let t=tests[q],ok=a===t.t;if(ok)score++;document.querySelectorAll('[data-a]').forEach(x=>x.disabled=true);document.getElementById('qr').innerHTML='<div class="pmRes '+(ok?'pmGood':'pmBad')+'"><b>'+(ok?'✅ Correto!':'❌ Não foi dessa vez.')+'</b><br>Resposta: <b>'+NN[N.indexOf(t.t)]+'</b></div>';setTimeout(()=>{q++;render()},650)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();